DATA = {
    'manĝi': {'pomo', 'pano', 'kuko', 'viando', 'fiŝo', 'legomo', 'fruktoj', 'supo', 'pasto', 'manĝaĵo', 'deserto', 'fromaĝo', 'rizo', 'ovo'},
    'trinki': {'akvo', 'kafo', 'teo', 'lakto', 'biero', 'vino', 'suko', 'limonado', 'ĉokolado', 'kokakolo', 'trinkaĵo', 'smoothie', 'koktelo'},
    'legi': {'libro', 'gazeto', 'letero', 'revuo', 'artikolo', 'poemo', 'romano', 'rakonto', 'teksto', 'novaĵo', 'retpaĝo', 'blogaĵo', 'dokumentoj', 'instrukcioj'},
    'skribi': {'letero', 'artikolo', 'libro', 'poemo', 'rakonto', 'romano', 'teksto', 'taglibro', 'raporto', 'eseo', 'mesaĝo', 'retpoŝto', 'scenaro', 'notoj'},
    'aĉeti': {'libro', 'pano', 'vestoj', 'donaco', 'manĝaĵo', 'trinkaĵo', 'mebloj', 'komputilo', 'telefono', 'aŭto', 'biletoj', 'ŝuoj', 'ludilo', 'aparato'},
    'vendi': {'domo', 'aŭto', 'libro', 'komputilo', 'mebloj', 'vestoj', 'telefono', 'manĝaĵo', 'trinkaĵo', 'biletoj', 'aparato', 'ludilo', 'ŝuoj'},
    'vidi': {'birdo', 'filmo', 'bildo', 'homo', 'spektaklo', 'prezentado', 'koncerto', 'teatro', 'pejzaĝo', 'ekspozicio', 'sunsubiro', 'arkitekturo', 'bestoj'},
    'aŭdi': {'muziko', 'voĉo', 'bruo', 'kanto', 'spektaklo', 'prezentado', 'koncerto', 'teatro', 'radio', 'birdokanto', 'tondro', 'trafiko', 'konversacio'},
    'ami': {'homo', 'kato', 'vivo', 'naturo', 'familio', 'amiko', 'arto', 'muziko', 'literaturo', 'laboro', 'sporto', 'bestoj', 'kulturo', 'lingvo'},
    'havi': {'domo', 'aŭto', 'laboro', 'tempo', 'mono', 'familio', 'amiko', 'komputilo', 'telefono', 'libro', 'ĝardeno', 'bestoj', 'hobio', 'plano'},
    'kuri': {'maratono', 'strato', 'parko', 'sportejo', 'vojo', 'arbaro', 'strando', 'montaro', 'stadiono', 'konkurso', 'distanco', 'tempo', 'celo'},
    'dormi': {'lito', 'hotelo', 'domo', 'matraco', 'tendo', 'hamako', 'sofo', 'dormosako', 'dormĉambro', 'aviadilo', 'trajno', 'aŭto', 'plaĝo'},
    'ludi': {'muziko', 'ludo', 'sporto', 'instrumento', 'teatro', 'karto', 'ŝako', 'pilko', 'videoludoj', 'rolludoj', 'gitaro', 'piano', 'drumo'},
    'naĝi': {'rivero', 'lago', 'naĝejo', 'oceano', 'maro', 'plaĝo', 'piscino', 'akvo', 'ondoj', 'strando'},
    'flugi': {'aviadilo', 'birdo', 'helikoptero', 'drono', 'papilio', 'insekto', 'raketo', 'balono', 'glisilo', 'aeroplano'},
    'kanti': {'kanto', 'himno', 'melodio', 'muziko', 'opero', 'koruso', 'voĉo', 'ritmo', 'koncerto', 'festivalo', 'karaokeo'},
    'danci': {'muziko', 'ritmo', 'scenejo', 'baleto', 'valso', 'tango', 'salso', 'diskoteko', 'festivalo', 'koncerto', 'teatro'},
    'labori': {'oficejo', 'fabriko', 'projekto', 'laboro', 'komputilo', 'tasko', 'esploro', 'raporto', 'kunlaboro', 'klientoj', 'dokumentoj', 'tempo', 'teamo'},
    'studi': {'libro', 'scienco', 'lernilo', 'fako', 'projekto', 'esploro', 'tasko', 'laboro', 'temo', 'kurso', 'universitato', 'ekzameno', 'diplomo'},
    'instrui': {'lingvo', 'matematiko', 'scienco', 'historio', 'geografio', 'fiziko', 'temo', 'klaso', 'lernanto', 'kurso', 'leciono', 'arto', 'sporto', 'muziko'},
    'pentri': {'bildo', 'pentraĵo', 'kanvaso', 'pejzaĝo', 'portreto', 'naturo', 'koloro', 'desegno', 'arto', 'murpentraĵo', 'akvarelo', 'oleo'},
    'fotografi': {'pejzaĝo', 'homo', 'naturo', 'urbo', 'arkitekturo', 'bestoj', 'floroj', 'maro', 'montoj', 'sunsubiro', 'portreto', 'evento', 'sporto', 'arto'},
    'kuiri': {'manĝaĵo', 'viando', 'fiŝo', 'legomo', 'supo', 'pasto', 'rizo', 'pico', 'kuko', 'deserto', 'spicoj', 'fruktoj', 'pano', 'fromaĝo'},
    'fari': {'laboro', 'projekto', 'devo', 'tasko', 'plano', 'decido', 'elekto', 'promeso', 'eraro', 'progreso', 'ŝanĝo'},
    'lavi': {'vestoj', 'aŭto', 'manoj', 'pladoj', 'fenestro', 'planko', 'tuko', 'haroj', 'korpo', 'telero', 'glaso'},
    'rigardi': {'televido', 'filmo', 'bildo', 'ekrano', 'spektaklo', 'teatro', 'koncerto', 'pejzaĝo', 'ekspozicio', 'stelo', 'sunsubiro'},
    'plori': {'filmo', 'doloro', 'malĝojo', 'situacio', 'perdo', 'funebro', 'adiaŭo', 'akcidento', 'rakonto', 'emocio'},
    'ridi': {'ŝerco', 'komedio', 'amiko', 'situacio', 'rakonto', 'filmo', 'teatro', 'prezentado', 'karnavalo', 'festo'},
    'kompreni': {'lingvo', 'ideo', 'frazo', 'situacio', 'problemo', 'klarigo', 'leciono', 'instruo', 'koncepto', 'signifo', 'demando'},
    'helpi': {'amiko', 'homo', 'projekto', 'tasko', 'problemo', 'studento', 'najbaro', 'kolego', 'familio', 'volontulo', 'bezonulo'},
    'danki': {'homo', 'donaco', 'servo', 'helpo', 'subteno', 'konsilo', 'amikeco', 'gastigo', 'invito', 'komplimento'},
    'pardoni': {'eraro', 'homo', 'kulpo', 'ofendo', 'konflikto', 'miskompreno', 'forgeso', 'malĝentileco', 'akcidento'},
    'forgesi': {'nomo', 'dato', 'tempo', 'loko', 'promeso', 'tasko', 'evento', 'vorto', 'numero', 'adreso', 'pasvorto'},
    'memori': {'dato', 'nomo', 'evento', 'loko', 'tempo', 'infaneco', 'vojaĝo', 'festo', 'renkontiĝo', 'sperto', 'leciono'},
    'renkonti': {'amiko', 'kolego', 'kliento', 'familiano', 'fremdulo', 'najbaro', 'profesoro', 'gasto', 'partnero', 'turisto'},
    'saluti': {'amiko', 'kolego', 'najbaro', 'gasto', 'fremdulo', 'profesoro', 'vendisto', 'studento', 'konato', 'turisto'},
    'inviti': {'gasto', 'amiko', 'familio', 'kolego', 'najbaro', 'kliento', 'partnero', 'studento', 'profesoro', 'artisto'},
    'viziti': {'urbo', 'lando', 'amiko', 'muzeo', 'parko', 'ekspozicio', 'galerio', 'familio', 'templo', 'kastelo', 'zoologiĝardeno'},
    'babili': {'amiko', 'kolego', 'najbaro', 'familiano', 'fremdulo', 'gasto', 'vendisto', 'taksisto', 'frizisto', 'studento'},
    'telefonadi': {'amiko', 'familio', 'kolego', 'kliento', 'kuracisto', 'advokato', 'vendisto', 'helpservo', 'asekuristo'},
    'provi': {'manĝaĵo', 'vesto', 'ŝuo', 'sporto', 'hobio', 'instrumento', 'lingvo', 'programo', 'metodo', 'tekniko', 'recepto'},
    'esperi': {'sukceso', 'feliĉo', 'sano', 'paco', 'amo', 'amikeco', 'laboro', 'rezulto', 'solvo', 'estonteco', 'ŝanĝo'},
    'klarigi': {'problemo', 'situacio', 'koncepto', 'regulo', 'metodo', 'sistemo', 'teorio', 'signifo', 'funkcio', 'rezulto'},
    'plani': {'vojaĝo', 'festo', 'kunveno', 'projekto', 'evento', 'kurso', 'kariero', 'konstruo', 'renovigo', 'ŝanĝo'},
    'organizi': {'evento', 'festo', 'kunveno', 'konferenco', 'koncerto', 'ekspozicio', 'konkurso', 'projekto', 'teamo', 'vojaĝo'},
    'konstrui': {'domo', 'ponto', 'strato', 'urbo', 'konstruaĵo', 'muro', 'ŝoseo', 'teatro', 'lernejo', 'fabriko'},
    'detrui': {'domo', 'ponto', 'muro', 'konstruaĵo', 'urbo', 'medio', 'espero', 'amikeco', 'konfido', 'reputacio'},
    'krei': {'arto', 'muziko', 'poemo', 'romano', 'filmo', 'programo', 'retejo', 'desegno', 'projekto', 'solvo'},
    'desegni': {'bildo', 'mapo', 'plano', 'skizo', 'portreto', 'pejzaĝo', 'diagramo', 'modelo', 'simbolo', 'logotipo'},
    'respondi': {'demando', 'letero', 'mesaĝo', 'retpoŝto', 'telefonvoko', 'peto', 'enketo', 'ekzameno', 'intervjuo'},
    'peti': {'helpo', 'konsilo', 'informo', 'permeso', 'pardono', 'tempo', 'mono', 'opinio', 'subteno', 'klarigo'},
    'prunti': {'libro', 'mono', 'aŭto', 'ilo', 'vestoj', 'filmo', 'ludilo', 'biciklo', 'komputilo', 'telefono'},
    'redoni': {'libro', 'mono', 'ŝlosilo', 'dokumento', 'ilo', 'vestoj', 'aŭto', 'telefono', 'komputilo', 'ludilo'},
    'ŝati': {'manĝaĵo', 'muziko', 'filmo', 'libro', 'sporto', 'arto', 'naturo', 'vojaĝo', 'hobio', 'amikeco'},
    'malŝati': {'bruo', 'malordemo', 'mensogo', 'malĝentileco', 'violento', 'milito', 'maljusteco', 'malamo', 'diskriminacio'},
    'bezoni': {'helpo', 'tempo', 'mono', 'konsilo', 'informo', 'subteno', 'ripozo', 'laboro', 'eduko', 'amo'},
    'serĉi': {'laboro', 'domo', 'informo', 'ŝlosilo', 'libro', 'dokumento', 'solvo', 'amiko', 'telefono', 'respondo'},
    'trovi': {'solvo', 'respondo', 'trezoro', 'ŝlosilo', 'amiko', 'laboro', 'domo', 'informo', 'feliĉo', 'amo'},
    'perdi': {'mono', 'tempo', 'ŝlosilo', 'dokumento', 'telefono', 'valizo', 'bileto', 'pasporto', 'okazo', 'espero'},
    'gajni': {'premio', 'konkurso', 'medalo', 'mono', 'respekto', 'famo', 'konfido', 'sperto', 'amiko', 'kono'},
    'malsukcesi': {'ekzameno', 'projekto', 'konkurso', 'intervjuo', 'provo', 'tasko', 'plano', 'celo', 'entrepreno'},
    'festi': {'naskiĝtago', 'geedziĝo', 'diplomiĝo', 'datreveno', 'sukceso', 'festo', 'kristnasko', 'novjaro', 'karnavalo'},
    'celebri': {'venko', 'sukceso', 'festo', 'evento', 'datreveno', 'naskiĝtago', 'geedziĝo', 'diplomiĝo', 'premio'},
    'partopreni': {'kunveno', 'konferenco', 'kurso', 'konkurso', 'projekto', 'festo', 'koncerto', 'sporto', 'diskuto', 'evento'},
    'kolekti': {'poŝtmarko', 'monero', 'bildo', 'libro', 'arto', 'informo', 'dato', 'pruvo', 'subskribo', 'donaco'},
    'aŭskulti': {'muziko', 'radio', 'novaĵo', 'prelego', 'koncerto', 'birdo', 'rakonto', 'konsilo', 'opinio', 'diskuto'},
    'demonstri': {'produkto', 'tekniko', 'metodo', 'kapablo', 'scio', 'talento', 'programo', 'aparato', 'sistemo', 'funkcio'},
    'gvidi': {'grupo', 'teamo', 'projekto', 'entrepreno', 'organizaĵo', 'ekskurso', 'kunveno', 'diskuto', 'kurso', 'trejnado'},
    'interesi': {'hobio', 'temo', 'scienco', 'arto', 'kulturo', 'sporto', 'muziko', 'literaturo', 'historio', 'teknologio'},
    'esplori': {'mondo', 'naturo', 'scienco', 'historio', 'kulturo', 'lingvo', 'spaco', 'maro', 'lando', 'problemo'},
    'loĝi': {'domo', 'apartamento', 'urbo', 'vilaĝo', 'lando', 'regiono', 'insulo', 'kvartalo', 'studenthejmo', 'hotelo'},
    'pripensi': {'propono', 'decido', 'solvo', 'problemo', 'ideo', 'plano', 'estonteco', 'situacio', 'demando', 'elekto'},
    'elekti': {'laboro', 'domo', 'lernejo', 'vojaĝo', 'manĝaĵo', 'vesto', 'amiko', 'partnero', 'hobio', 'vojo'},
    'juĝi': {'konkurso', 'ekzameno', 'prezentado', 'debato', 'kvalito', 'rezulto', 'konduto', 'laboro', 'talento', 'arto'},
    'kritiki': {'laboro', 'konduto', 'decido', 'politiko', 'filmo', 'libro', 'muziko', 'arto', 'projekto', 'metodo'},
    'admiri': {'talento', 'beleco', 'kuraĝo', 'saĝeco', 'honesteco', 'kreemo', 'persistemo', 'pacienco', 'kompetenteco'},
    'lerni': {'lingvo', 'matematiko', 'scienco', 'historio', 'geografio', 'fiziko', 'temo', 'kurso', 'leciono', 'arto', 'sporto', 'muziko', 'tekniko', 'kulturo'},
    'ekspliki': {'problemo', 'situacio', 'koncepto', 'teorio', 'metodo', 'sistemo', 'regulo', 'fenomeno', 'funkcio', 'signifo'}
}