DATA = {
    'manĝi': {'pomo', 'pano', 'kuko', 'viando', 'fiŝo', 'legomo', 'fruktoj', 'supo', 'pasto', 'manĝaĵo', 'deserto', 'fromaĝo', 'rizo', 'ovo'},
    'trinki': {'akvo', 'kafo', 'teo', 'lakto', 'biero', 'vino', 'suko', 'limonado', 'ĉokolado', 'kokakolo', 'trinkaĵo', 'smoothie', 'koktelo'},
    'legi': {'libro', 'gazeto', 'letero', 'revuo', 'artikolo', 'poemo', 'romano', 'rakonto', 'teksto', 'novaĵo', 'retpaĝo', 'blogaĵo', 'dokumentoj', 'instrukcioj'},
    'skribi': {'letero', 'artikolo', 'libro', 'poemo', 'rakonto', 'romano', 'teksto', 'taglibro', 'raporto', 'eseo', 'mesaĝo', 'retpoŝto', 'scenaro', 'notoj'},
    'aĉeti': {'libro', 'pano', 'vestoj', 'donaco', 'manĝaĵo', 'trinkaĵo', 'mebloj', 'komputilo', 'telefono', 'aŭto', 'biletoj', 'ŝuoj', 'ludilo', 'aparato'},
    'vendi': {'domo', 'aŭto', 'libro', 'komputilo', 'mebloj', 'vestoj', 'telefono', 'manĝaĵo', 'trinkaĵo', 'biletoj', 'aparato', 'ludilo', 'ŝuoj'},
    'vidi': {'birdo', 'filmo', 'bildo', 'homo', 'spektaklo', 'prezentado', 'koncerto', 'teatro', 'pejzaĝo', 'ekspozicio', 'sunsubiro', 'arkitekturo', 'bestoj'},
    'aŭdi': {'muziko', 'voĉo', 'bruo', 'kanto', 'spektaklo', 'prezentado', 'koncerto', 'teatro', 'radio', 'birdokanto', 'tondro', 'trafiko', 'konversacio'},
    'ami': {'homo', 'kato', 'vivo', 'naturo', 'familio', 'amiko', 'arto', 'muziko', 'literaturo', 'laboro', 'sporto', 'bestoj', 'kulturo', 'lingvo'},
    'havi': {'domo', 'aŭto', 'laboro', 'tempo', 'mono', 'familio', 'amiko', 'komputilo', 'telefono', 'libro', 'ĝardeno', 'bestoj', 'hobio', 'plano'},
    'kuri': {'maratono', 'strato', 'parko', 'sportejo', 'vojo', 'arbaro', 'strando', 'montaro', 'stadiono', 'konkurso', 'distanco', 'tempo', 'celo'},
    'dormi': {'lito', 'hotelo', 'domo', 'matraco', 'tendo', 'hamako', 'sofo', 'dormosako', 'dormĉambro', 'aviadilo', 'trajno', 'aŭto', 'plaĝo'},
    'ludi': {'muziko', 'ludo', 'sporto', 'instrumento', 'teatro', 'karto', 'ŝako', 'pilko', 'videoludoj', 'rolludoj', 'gitaro', 'piano', 'drumo'},
    'naĝi': {'rivero', 'lago', 'naĝejo', 'oceano'},
    'flugi': {'aviadilo', 'birdo', 'helikoptero', 'drono'},
    'kanti': {'kanto', 'himno', 'melodio', 'muziko'},
    'danci': {'muziko', 'ritmo', 'scenejo', 'baletado'},
    'labori': {'oficejo', 'fabriko', 'projekto', 'laboro', 'komputilo', 'tasko', 'esploro', 'raporto', 'kunlaboro', 'klientoj', 'dokumentoj', 'tempo', 'teamo'},
    'studi': {'libro', 'scienco', 'lernilo', 'fako', 'projekto', 'esploro', 'tasko', 'laboro', 'temo', 'kurso', 'universitato', 'ekzameno', 'diplomo'},
    'instrui': {'lingvo', 'matematiko', 'scienco', 'historio', 'geografio', 'fiziko', 'temo', 'klaso', 'lernanto', 'kurso', 'leciono', 'arto', 'sporto', 'muziko'},
    'pentri': {'bildo', 'pentraĵo', 'kanvaso', 'pejzaĝo'},
    'fotografi': {'pejzaĝo', 'homo', 'naturo', 'urbo', 'arkitekturo', 'bestoj', 'floroj', 'maro', 'montoj', 'sunsubiro', 'portreto', 'evento', 'sporto', 'arto'},
    'kuiri': {'manĝaĵo', 'viando', 'fiŝo', 'legomo', 'supo', 'pasto', 'rizo', 'pico', 'kuko', 'deserto', 'spicoj', 'fruktoj', 'pano', 'fromaĝo'},
    'fari': {'laboro', 'projekto', 'devo', 'tasko'},
    'lavi': {'vestoj', 'aŭto', 'manoj', 'pladoj'},
    'rigardi': {'televido', 'filmo', 'bildo', 'ekrano'},
    'plori': {'filmo', 'doloro', 'malĝojo', 'situacio'},
    'ridi': {'filmo', 'amiko', 'sperto', 'humoro'},
    'kompreni': {'lingvo', 'ideo', 'frazo', 'situacio'},
    'helpi': {'amiko', 'homo', 'projekto', 'tasko'},
    'danki': {'homo', 'donaco', 'servo', 'afablaĵo'},
    'pardoni': {'eraro', 'homo', 'misago', 'situacio'},
    'forgesi': {'dato', 'nomo', 'sperto', 'informo'},
    'memori': {'dato', 'nomo', 'eventoj', 'memoroj'},
    'renkonti': {'amiko', 'fremdulo', 'homo', 'kolego'},
    'saluti': {'amiko', 'homo', 'kolego', 'gastoj'},
    'inviti': {'homo', 'amiko', 'gastoj', 'kolego'},
    'viziti': {'urbo', 'lando', 'amiko', 'muzeo'},
    'movi': {'tablo', 'seĝo', 'aŭto', 'meblo'},
    'porti': {'vestaĵo', 'sako', 'dorso', 'pakaĵo'},
    'babili': {'amiko', 'homo', 'grupo', 'temo'},
    'telefonadi': {'amiko', 'kliento', 'familiano', 'kolego'},
    'provi': {'manĝo', 'projekto', 'ludo', 'eksperimento'},
    'esperi': {'rezulto', 'venko', 'feliĉo', 'solvo'},
    'timigi': {'infano', 'homo', 'birdo', 'bestoj'},
    'eviti': {'problemo', 'danĝero', 'konflikto', 'akcidento'},
    'klarigi': {'ideo', 'situacio', 'plano', 'frazo'},
    'plani': {'ferio', 'projekto', 'evento', 'tasko'},
    'organizi': {'evento', 'kunveno', 'projekto', 'festeno'},
    'konstrui': {'domo', 'ponto', 'projekto', 'fabriko'},
    'detrui': {'domo', 'projekto', 'ponto', 'lando'},
    'krei': {'arto', 'ideo', 'projekto', 'muziko'},
    'desegni': {'plano', 'bildo', 'arkitekturo', 'skemo'},
    'demandi': {'demando', 'informo', 'kialo', 'ideo'},
    'respondi': {'demando', 'letero', 'informo', 'telefono'},
    'peti': {'helpo', 'informo', 'servo', 'dono'},
    'prunti': {'libro', 'mono', 'aŭto', 'vestoj'},
    'redoni': {'libro', 'mono', 'posedaĵo', 'pruntaĵo'},
    'ŝati': {'manĝo', 'muziko', 'libro', 'filmo'},
    'malŝati': {'manĝo', 'muziko', 'filmo', 'ideo'},
    'preferi': {'koloro', 'muziko', 'manĝo', 'vestaĵo'},
    'bezoni': {'tempo', 'mono', 'laboro', 'informo'},
    'serĉi': {'informo', 'laboro', 'objekto', 'ideo'},
    'trovi': {'solvo', 'informo', 'objekto', 'loko'},
    'perdi': {'objekto', 'informo', 'tempo', 'mono'},
    'gajni': {'premio', 'ludo', 'laboro', 'respekto'},
    'malsukcesi': {'projekto', 'ludo', 'eksperimento', 'provo'},
    'festi': {'evento', 'naskiĝo', 'venko', 'ferio'},
    'celebri': {'evento', 'venko', 'ferio', 'memorindaĵo'},
    'partopreni': {'kunveno', 'kurso', 'evento', 'projekto'},
    'kolekti': {'stampoj', 'informo', 'artefaktoj', 'datoj'},
    'aŭskulti': {'muziko', 'prelego', 'rakonto', 'novaĵo'},
    'demonstri': {'tekniko', 'ideo', 'projekto', 'kapablo'},
    'gvidi': {'grupo', 'ekskurso', 'projekto', 'homo'},
    'renkonti': {'amiko', 'kolego', 'kliento', 'familiano'},
    'interesi': {'fako', 'ideo', 'temo', 'aktivado'},
    'esplori': {'problemo', 'fenomeno', 'spaco', 'naturo'},
    'loĝi': {'domo', 'urbo', 'regiono', 'lando'},
    'fari': {'tasko', 'projekto', 'eksperimento', 'laboro'},
    'pripensi': {'problemo', 'solvo', 'ideo', 'situacio'},
    'elekti': {'opcio', 'solvo', 'gvidanto', 'alternativo'},
    'juĝi': {'homo', 'ideo', 'rezulto', 'prezentado'},
    'kritiki': {'ideo', 'projekto', 'prezento', 'laboro'},
    'admiri': {'arto', 'naturo', 'homo', 'ideoj'},
    'lerni': {'lingvo', 'matematiko', 'scienco', 'historio', 'geografio', 'fiziko', 'temo', 'kurso', 'leciono', 'arto', 'sporto', 'muziko', 'tekniko', 'kulturo'},
    'ekspliki': {'ideo', 'fako', 'solvo', 'problemo'}
}